# GLAB-386.3.9 - Adding new column to existing DataFrame in Pandas

In [25]:
import numpy as np
import pandas as pd

In [37]:
# Define a dictionary containing Students data and their respective details
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Score 1' : [56,86,77,45],
        'Score 2' : [50,96,60,30]}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

In [27]:
print('Data Frame Before New Column:')
df.head()

Data Frame Before New Column:

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [38]:
# a list that is to be converted into a column
address = ['NYC', 'NJ', 'CA', 'PA']

# Declare a list that is to be converted into a column
address = ['NYC', 'NJ', 'CA', 'PA']

In [39]:
# adding a address column to the dataframe
df['Address'] = address

print("Data Frame After New Column:")
# Observe the result
df.head()
# in this program the address column is added in hte last position

Data Frame After New Column:

     Name  Height Qualification  Score 1  Score 2 Address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

In [40]:
# defining a dictionary containing Students data and their respective details
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
           'Score 2' : [50,96,60,30]}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
print("Data Frame Before Adding Column:")
print(df)
print("Data Frame After Adding Column:")
df['Total_Score'] = df['Score 1'] +  df['Score 2']

print(df)

Data Frame Before Adding Column:
     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30
Data Frame After Adding Column:
     Name  Height Qualification  Score 1  Score 2  Total_Score
0    Jane     5.1           Msc       56       50          106
1  Princi     6.2            MA       86       96          182
2   James     5.1           Msc       77       60          137
3    Fadi     5.2           Msc       45       30           75

In [41]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
           'Score 2' : [50,96,60,30]}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
print("------before -------")
print(df)
print("------after adding column -------")
#
df['Total_Score'] = df['Score 1'] +  df['Score 2']
df['Total_Score_average'] = df['Total_Score']/ 2
df.head()

------before -------
     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30
------after adding column -------

,Name,Height,Qualification,Score 1,Score 2,Total_Score,Total_Score_average
0,Jane,5.1,Msc,56,50,106,53.0
1,Princi,6.2,MA,86,96,182,91.0
2,James,5.1,Msc,77,60,137,68.5
3,Fadi,5.2,Msc,45,30,75,37.5

### Importing Specified Columns AND Rearranging them

In [42]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
           'Score 2' : [50,96,60,30]}

df2 = pd.DataFrame(data, columns=['Score 1','Score 2', 'Name', 'Qualification'])
print(df2)

   Score 1  Score 2    Name Qualification
0       56       50    Jane           Msc
1       86       96  Princi            MA
2       77       60   James           Msc
3       45       30    Fadi           Msc

In [43]:
values = [['Rohan', 455], ['Elvish', 250], ['John', 495],
          ['Sai', 400], ['Eric', 350], ['Adam', 450]]

df3 = pd.DataFrame(values, columns=['Name', 'Univ_Marks'])

df3.head()

     Name  Univ_Marks
0   Rohan         455
1  Elvish         250
2    John         495
3     Sai         400
4    Eric         350

In [44]:
# Will compute percent grade of their university marks
df3['Percentages'] = (df3['Univ_Marks'] / 500) * 100

df3.head()

     Name  Univ_Marks  Percentages
0   Rohan         455         91.0
1  Elvish         250         50.0
2    John         495         99.0
3     Sai         400         80.0
4    Eric         350         70.0

### Using the insert() to add a column

In [35]:
df3.insert(1,'Age', [1000,2000, 50, 60, 12, 13])

df3.head()

     Name   Age  Univ_Marks  Percentages
0   Rohan  1000         455         91.0
1  Elvish  2000         250         50.0
2    John    50         495         99.0
3     Sai    60         400         80.0
4    Eric    12         350         70.0

In [36]:
df3 = df3.assign(location=['MiddleEarth', 'Forgotten Lands', 'NYC', 'NJ', 'CA', 'MA'])
df3.head()

     Name   Age  Univ_Marks  Percentages         location
0   Rohan  1000         455         91.0      MiddleEarth
1  Elvish  2000         250         50.0  Forgotten Lands
2    John    50         495         99.0              NYC
3     Sai    60         400         80.0               NJ
4    Eric    12         350         70.0               CA